#!/usr/bin/env node
// Build the Astra DB MCP server package:
//  1. ui/ → one self-contained app shell (CSS + JS inlined) → src/generated/ui.ts
//  2. skills/ + hooks/ + example catalog → src/generated/assets.json (+ dist/assets.json)
//  3. src/cli/index.ts → dist/cli.js (single file, all dependencies bundled) + THIRD_PARTY_NOTICES.md
//
//   node scripts/build.mjs [--ui-only]
import { build } from "esbuild";
import { chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const repo = join(root, "..");
const uiOnly = process.argv.includes("--ui-only");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const APP_HTML_BUDGET = 150 * 1024;

// 1. app shell ------------------------------------------------------------------
const js = await build({
  entryPoints: [join(root, "ui/src/main.ts")],
  bundle: true, format: "iife", platform: "browser", target: "es2020", write: false, minify: true, legalComments: "none",
});
const css = await build({
  entryPoints: [join(root, "ui/styles.css")], bundle: true, minify: true, write: false, loader: { ".css": "css" },
});
const html = readFileSync(join(root, "ui/index.html"), "utf8")
  // Replacer functions: literal insertion (plain strings would interpret `$&` inside the bundle).
  .replace("/*@css*/", () => css.outputFiles[0].text.trim())
  .replace("/*@js*/", () => js.outputFiles[0].text.trim().replace(/<\/script/gi, "<\\/script"));
if (html.length > APP_HTML_BUDGET) throw new Error(`app shell is ${html.length} bytes (budget ${APP_HTML_BUDGET})`);
mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/ui.ts"),
  `// Generated by scripts/build.mjs — do not edit.\nexport const APP_HTML = ${JSON.stringify(html)};\n`);
console.log(`app shell: ${(html.length / 1024).toFixed(1)} KB`);

// 2. bundled plugin assets (skills + hooks + example catalog) ------------------------
const assets = { version: pkg.version, files: {}, catalog: [] };
const indexer = join(repo, "scripts/build-examples-index.mjs");
if (existsSync(indexer)) {
  const { catalog } = await import(pathToFileURL(indexer).href);
  assets.catalog = catalog();
  const walk = (dir) => {
    for (const name of readdirSync(join(repo, dir))) {
      const rel = `${dir}/${name}`;
      if (statSync(join(repo, rel)).isDirectory()) walk(rel);
      else assets.files[rel] = readFileSync(join(repo, rel), "utf8");
    }
  };
  for (const dir of ["skills", "hooks"]) if (existsSync(join(repo, dir))) walk(dir);
} else {
  console.warn("skills/ not found next to server/: code_examples and Bob bundles will be unavailable in this build");
}
const assetsJson = JSON.stringify(assets);
writeFileSync(join(root, "src/generated/assets.json"), assetsJson);
console.log(`assets: ${Object.keys(assets.files).length} files, ${assets.catalog.length} examples (${(assetsJson.length / 1024 / 1024).toFixed(1)} MB)`);

if (uiOnly) process.exit(0);

// 3. CLI bundle -------------------------------------------------------------------
mkdirSync(join(root, "dist"), { recursive: true });
const result = await build({
  entryPoints: [join(root, "src/cli/index.ts")],
  outfile: join(root, "dist/cli.js"),
  bundle: true, platform: "node", format: "esm", target: "node20", minify: true, keepNames: true, mainFields: ["module", "main"],
  sourcemap: false, legalComments: "none", metafile: true,
  define: { __ASTRA_MCP_VERSION__: JSON.stringify(pkg.version) },
  banner: { js: "#!/usr/bin/env node\nimport { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
  logLevel: "warning",
});
chmodSync(join(root, "dist/cli.js"), 0o755);
// npm package extras: license and vendored-content attribution next to package.json.
for (const name of ["LICENSE", "NOTICE"]) {
  if (existsSync(join(repo, name))) writeFileSync(join(root, name), readFileSync(join(repo, name)));
}
writeFileSync(join(root, "dist/assets.json"), assetsJson);

// Third-party notices for everything bundled into dist/cli.js.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  const match = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)\//);
  if (match && !packages.has(match[1])) packages.set(match[1], join(root, "node_modules", match[1]));
}
const notices = ["# Third-party notices", "", `dist/cli.js bundles the following packages (with ${pkg.name} ${pkg.version}).`, ""];
for (const [name, dir] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
  let meta = {};
  try { meta = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")); } catch {}
  const licenseFile = existsSync(dir) ? readdirSync(dir).find((f) => /^(licen[cs]e|copying)/i.test(f)) : undefined;
  notices.push(`## ${name}${meta.version ? ` ${meta.version}` : ""}`, "", `License: ${meta.license ?? "see package"}`, "");
  if (licenseFile) notices.push("```", readFileSync(join(dir, licenseFile), "utf8").trim(), "```", "");
}
writeFileSync(join(root, "THIRD_PARTY_NOTICES.md"), `${notices.join("\n")}\n`);
const size = readFileSync(join(root, "dist/cli.js")).length;
console.log(`dist/cli.js: ${(size / 1024).toFixed(0)} KB, ${packages.size} bundled packages (${relative(root, join(root, "THIRD_PARTY_NOTICES.md"))})`);
